### ISSUE TITLE
Install fails in node 0.12

### ISSUE THREAD

**Issue by grit96** [gtramontina/ghooks#107]
`npm install ghooks` fails in node 0.12 because of the use of `const` in the install script:

```
> ghooks@1.2.2 install /tmp/node_modules/ghooks
> opt --out ghooks-install --exec "node ./bin/install"

/tmp/node_modules/ghooks/node_modules/path-exists/index.js:2
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/node_modules/ghooks/bin/install:2:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/geraint/.nvm/versions/node/v0.12.14/bin/node" "/home/geraint/.nvm/versions/node/v0.12.14/bin/npm" "install" "ghooks"
npm ERR! node v0.12.14
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
```

**Comment by kentcdodds** [comment]
Huh, interesting looks like this is a problem with path-exists. In the latest version they dropped support for 0.12. So we need to go back a version I think to `2.1.0`.

**Comment by kentcdodds** [comment]
Please let me know if this doesn't fix your use case!

**Comment by grit96** [comment]
Thanks, that's fixed it.
