### ISSUE TITLE
Can't install under a submodule

### ISSUE THREAD

**Issue by lferreirawork** [gtramontina/ghooks#46]
When installing under a git [submodule](https://git-scm.com/docs/git-submodule), `installHooks()` correctly finds a .git folder (for the submodule), but can't `resolve(gitRoot, '.git/hooks')`, resulting in the following error:

```
fs.js:747
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: ENOTDIR, not a directory '/testproject/submodule/.git/hooks'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at ensureHooksDirExists (/testproject/submodule/node_modules/ghooks/lib/install.js:78:38)
    at installHooks (/testproject/submodule/node_modules/ghooks/lib/install.js:41:5)
    at Object.<anonymous> (/testproject/submodule/node_modules/ghooks/bin/install:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by kentcdodds** [comment]
After looking into it a little bit, git references githooks in a different directory for submodules. I think we could use something [like this](http://stackoverflow.com/a/14073454/971592) to identify the correct directory to install our githooks.

Would you be willing to [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by leandroferreira** [comment]
@kentcdodds will do

**Comment by ta2edchimp** [comment]
@leandroferreira @lferreirawork is this something you're actively working on?
If not, I'd be willing to take over.

A result may also relate to a possible solution for #66

**Comment by leandroferreira** [comment]
@ta2edchimp all yours!

**Comment by ta2edchimp** [comment]
Thanks for the feedback!
